### ISSUE TITLE
txt dosyasından url çekme

### ISSUE THREAD

**Issue by ghost** [ekremcet/WhisperTranscribe#1]
Abi selam, proje için teşekkür ederim, sistem dandik oldugu için google colabden hallediyorum işimi, url.txt diye dosya belirtsek urlleri ordan çekse transcribe edilen videonun urlsi txtden silinse muazzam olur bunu ekleme şansın var mı?

**Comment by ekremcet** [comment]
Aslında güzel olur dediğin gibi, ekleyeyim bir ara onu.

Onu bekleyene kadar da şu şekilde Colab'da çalıştırabilirsin. Ben de genelde colab üzerinde kullanıyorum zaten repoyu. Biraz gereksiz uğraş, her seferinde link-isim değişmen gerekiyor ama ama en azından iş görüyor şimdilik.
<img width="680" alt="Screenshot 2022-12-12 at 10 31 51" src="https://user-images.githubusercontent.com/16050225/207011187-7c6cd45f-5110-4330-933e-91ffabc79589.png">

**Comment by toprak** [comment]
Abi arthur diye birisi var onun notebooku evirdim cevirdim yaptım tek problem her transcriptionı aldıgımda onu transcribed videoya almasını istiyorum ama o bi transcribed videoyu birden çok defa alıyor onun dısı problemsiz gibi kodu atsam ona bakabilir misin 2 dakika, manuel google driveını mountlamayı unutma ama notebooku kendin kaydedeip sol taraftan mount edersen sürekli kendi oto yapıyo amac o ondan. https://paste.ee/p/UYCig
[
14]
print(transcribed_videos)

['https://www.youtube.com/watch?v=wh1obvttMPI', 'https://www.youtube.com/watch?v=wh1obvttMPI', 'https://www.youtube.com/watch?v=wh1obvttMPI']
print(url_list)

['https://www.youtube.com/watch?v=SA1vUln57yc', 'https://www.youtube.com/watch?v=M8147-9BBR8', 'https://www.youtube.com/watch?v=Df8j8U7aD8U']
